"""Shared in-memory SQLite executor.

Runs a list of context statements (typically CREATE TABLE / INSERT INTO) followed by a
SQL query against a fresh in-memory SQLite database. Used both to locally verify the
sql_context generated by gen_training_data.py and to execute an agent's chosen SQL
candidate.
"""
from __future__ import annotations

import functools
import sqlite3
from collections import Counter
from dataclasses import dataclass
from typing import Sequence

import sqlglot
import sqlglot.expressions as exp


@dataclass(frozen=True)
class ExecutionResult:
    success: bool
    columns: tuple[str, ...] | None
    rows: tuple[tuple, ...] | None
    error: str | None


@functools.lru_cache(maxsize=None)
def _is_insert(statement: str) -> bool:
    try:
        return isinstance(sqlglot.parse_one(statement, dialect="sqlite"), exp.Insert)
    except Exception:
        # Same lenient fallback as gretel.py's split_sql_context — a handful of context
        # statements use syntax sqlglot's sqlite dialect rejects.
        return statement.strip().upper().startswith("INSERT")


def clean_context(context_statements: Sequence[str]) -> tuple[str, ...]:
    """Drops INSERT statements from context_statements, keeping only schema-defining
    ones (CREATE TABLE and any other non-INSERT statement, e.g. CREATE VIEW/INDEX) — the
    schema an LLM/RM needs to reason about a query, without the sample-data noise that
    isn't relevant to whether a candidate SQL query is well-formed for that schema.
    Sample data is still needed for execution/QA-accuracy checks, so callers that
    execute SQL should keep using the original context_statements, not this."""
    return tuple(s for s in context_statements if not _is_insert(s))


def run_sql(context_statements: Sequence[str], sql: str, timeout: float = 5.0) -> ExecutionResult:
    conn = sqlite3.connect(":memory:", timeout=timeout)
    try:
        cursor = conn.cursor()
        for statement in context_statements:
            cursor.execute(statement)
        cursor.execute(sql)
        if cursor.description is not None:
            columns = tuple(col[0] for col in cursor.description)
            rows = tuple(cursor.fetchall())
        else:
            columns, rows = None, None
        conn.commit()
        return ExecutionResult(success=True, columns=columns, rows=rows, error=None)
    except sqlite3.Error as exc:
        return ExecutionResult(success=False, columns=None, rows=None, error=str(exc))
    finally:
        conn.close()


def capture_db_state(context_statements: Sequence[str], sql: str, timeout: float = 5.0) -> tuple[bool, dict[str, Counter] | None]:
    """Executes context_statements followed by sql against a fresh in-memory SQLite DB,
    then returns (True, state) where state is {table_or_view_name: Counter(rows)}
    covering every row of every table/view afterward — or (False, None) on any
    execution error.

    For a statement that doesn't return a result set (UPDATE/DELETE/INSERT/CREATE VIEW/
    etc — run_sql's rows is None for these), comparing two such statements' rows tells
    you nothing: both are None regardless of what the statements actually did. This
    compares their *effect* on the database instead. Counter (not a plain set) so
    duplicate rows in a table aren't collapsed into one when comparing.
    """
    conn = sqlite3.connect(":memory:", timeout=timeout)
    try:
        cursor = conn.cursor()
        for statement in context_statements:
            cursor.execute(statement)
        cursor.execute(sql)
        conn.commit()
        cursor.execute("SELECT name FROM sqlite_master WHERE type IN ('table', 'view')")
        names = [row[0] for row in cursor.fetchall()]
        state = {}
        for name in names:
            cursor.execute(f'SELECT * FROM "{name}"')
            state[name] = Counter(cursor.fetchall())
        return True, state
    except sqlite3.Error:
        return False, None
    finally:
        conn.close()
